/**
 * GENERATED FILE — do not edit by hand.
 *   npm run generate:cfb-logos
 *
 * Source: ESPN college-football team data, FBS group 80.
 *   season        2025
 *   generated     2026-10-09
 *   FBS teams     136 (of 762 across all divisions)
 *   keys          154
 *   gaps          1
 *
 * Every id below came from ESPN's own team record. None was typed by hand.
 * Notably this is how the Ohio split is verified rather than assumed:
 *   OSU  = Ohio State Buckeyes (ESPN id 194)
 *   OHIO = Ohio Bobcats        (ESPN id 195)
 * The school manifest's "OHIO" means Ohio University, so the old
 * hand-typed map pointed it at Ohio State's logo.
 */

/** ESPN's 500px team logo endpoint. `{id}` is a CFB_TEAM_LOGO_IDS value. */
export const CFB_LOGO_URL_PATTERN = "https://a.espncdn.com/i/teamlogos/ncaa/500/{id}.png";

/** Canonical CFB abbreviation -> ESPN numeric team id. */
export const CFB_TEAM_LOGO_IDS: Readonly<Record<string, number>> = {
  AF: 2005,
  AFA: 2005,
  AKR: 2006,
  ALA: 333,
  APP: 2026,
  ARIZ: 12,
  ARK: 8,
  ARMY: 349,
  ARST: 2032,
  ASU: 9,
  AUB: 2,
  BALL: 2050,
  BAY: 239,
  BC: 103,
  BGSU: 189,
  BOIS: 68,
  BSU: 68,
  BUF: 2084,
  BUFF: 2084,
  BYU: 252,
  CAL: 25,
  CCU: 324,
  CIN: 2132,
  CLEM: 228,
  CLT: 2429,
  CMU: 2117,
  COL: 38,
  COLO: 38,
  CONN: 41,
  CSU: 36,
  DEL: 48,
  DUKE: 150,
  ECU: 151,
  EMU: 2199,
  FAU: 2226,
  FINT: 2229,
  FIU: 2229,
  FLA: 57,
  FRES: 278,
  FSU: 52,
  GASO: 290,
  GAST: 2247,
  GT: 59,
  HAW: 62,
  HOU: 248,
  ILL: 356,
  IND: 84,
  IOWA: 2294,
  ISU: 66,
  IU: 84,
  JMU: 256,
  JSU: 55,
  JXST: 55,
  KENN: 338,
  KENT: 2309,
  KSU: 2306,
  KU: 2305,
  LATECH: 2348,
  LIB: 2335,
  LOU: 97,
  LSU: 99,
  LT: 2348,
  "M-OH": 193,
  MASS: 113,
  MD: 120,
  MEM: 235,
  MIA: 2390,
  MICH: 130,
  MINN: 135,
  MIOH: 193,
  MISS: 145,
  MIZ: 142,
  MOST: 2623,
  MRSH: 276,
  MSST: 344,
  MSU: 127,
  MTSU: 2393,
  NAVY: 2426,
  NCST: 152,
  NCSU: 152,
  ND: 87,
  NEB: 158,
  NEV: 2440,
  NIU: 2459,
  NMST: 166,
  NMSU: 166,
  NU: 77,
  NW: 77,
  ODU: 295,
  OHIO: 195,
  OKST: 197,
  ORE: 2483,
  ORST: 204,
  OSU: 194,
  OU: 201,
  PITT: 221,
  PSU: 213,
  PUR: 2509,
  RICE: 242,
  RUT: 164,
  RUTG: 164,
  SC: 2579,
  SDSU: 21,
  SHSU: 2534,
  SJSU: 23,
  SMU: 2567,
  SOAL: 6,
  STAN: 24,
  SYR: 183,
  "TA&M": 245,
  TAMU: 245,
  TCU: 2628,
  TEM: 218,
  TENN: 2633,
  TEX: 251,
  TLSA: 202,
  TOL: 2649,
  TROY: 2653,
  TTU: 2641,
  TUL: 2655,
  TULN: 2655,
  TXST: 326,
  UAB: 5,
  UCF: 2116,
  UCLA: 26,
  UGA: 61,
  UK: 96,
  UL: 309,
  ULL: 309,
  ULM: 2433,
  UNC: 153,
  UNLV: 2439,
  UNM: 167,
  UNT: 249,
  USA: 6,
  USC: 30,
  USF: 58,
  USM: 2572,
  USU: 328,
  UTAH: 254,
  UTEP: 2638,
  UTSA: 2636,
  UVA: 258,
  VAN: 238,
  VT: 259,
  WAKE: 154,
  WASH: 264,
  WCU: 2717,
  WIS: 275,
  WKU: 98,
  WMU: 2711,
  WSU: 265,
  WVU: 277,
  WYO: 2751,
};

/** Abbreviation -> ESPN displayName. Used by tests to prove each key is one school. */
export const CFB_TEAM_NAMES: Readonly<Record<string, string>> = {
  AF: "Air Force Falcons",
  AFA: "Air Force Falcons",
  AKR: "Akron Zips",
  ALA: "Alabama Crimson Tide",
  APP: "App State Mountaineers",
  ARIZ: "Arizona Wildcats",
  ARK: "Arkansas Razorbacks",
  ARMY: "Army Black Knights",
  ARST: "Arkansas State Red Wolves",
  ASU: "Arizona State Sun Devils",
  AUB: "Auburn Tigers",
  BALL: "Ball State Cardinals",
  BAY: "Baylor Bears",
  BC: "Boston College Eagles",
  BGSU: "Bowling Green Falcons",
  BOIS: "Boise State Broncos",
  BSU: "Boise State Broncos",
  BUF: "Buffalo Bulls",
  BUFF: "Buffalo Bulls",
  BYU: "BYU Cougars",
  CAL: "California Golden Bears",
  CCU: "Coastal Carolina Chanticleers",
  CIN: "Cincinnati Bearcats",
  CLEM: "Clemson Tigers",
  CLT: "Charlotte 49ers",
  CMU: "Central Michigan Chippewas",
  COL: "Colorado Buffaloes",
  COLO: "Colorado Buffaloes",
  CONN: "UConn Huskies",
  CSU: "Colorado State Rams",
  DEL: "Delaware Blue Hens",
  DUKE: "Duke Blue Devils",
  ECU: "East Carolina Pirates",
  EMU: "Eastern Michigan Eagles",
  FAU: "Florida Atlantic Owls",
  FINT: "Florida International Panthers",
  FIU: "Florida International Panthers",
  FLA: "Florida Gators",
  FRES: "Fresno State Bulldogs",
  FSU: "Florida State Seminoles",
  GASO: "Georgia Southern Eagles",
  GAST: "Georgia State Panthers",
  GT: "Georgia Tech Yellow Jackets",
  HAW: "Hawai'i Rainbow Warriors",
  HOU: "Houston Cougars",
  ILL: "Illinois Fighting Illini",
  IND: "Indiana Hoosiers",
  IOWA: "Iowa Hawkeyes",
  ISU: "Iowa State Cyclones",
  IU: "Indiana Hoosiers",
  JMU: "James Madison Dukes",
  JSU: "Jacksonville State Gamecocks",
  JXST: "Jacksonville State Gamecocks",
  KENN: "Kennesaw State Owls",
  KENT: "Kent State Golden Flashes",
  KSU: "Kansas State Wildcats",
  KU: "Kansas Jayhawks",
  LATECH: "Louisiana Tech Bulldogs",
  LIB: "Liberty Flames",
  LOU: "Louisville Cardinals",
  LSU: "LSU Tigers",
  LT: "Louisiana Tech Bulldogs",
  "M-OH": "Miami (OH) RedHawks",
  MASS: "Massachusetts Minutemen",
  MD: "Maryland Terrapins",
  MEM: "Memphis Tigers",
  MIA: "Miami Hurricanes",
  MICH: "Michigan Wolverines",
  MINN: "Minnesota Golden Gophers",
  MIOH: "Miami (OH) RedHawks",
  MISS: "Ole Miss Rebels",
  MIZ: "Missouri Tigers",
  MOST: "Missouri State Bears",
  MRSH: "Marshall Thundering Herd",
  MSST: "Mississippi State Bulldogs",
  MSU: "Michigan State Spartans",
  MTSU: "Middle Tennessee Blue Raiders",
  NAVY: "Navy Midshipmen",
  NCST: "NC State Wolfpack",
  NCSU: "NC State Wolfpack",
  ND: "Notre Dame Fighting Irish",
  NEB: "Nebraska Cornhuskers",
  NEV: "Nevada Wolf Pack",
  NIU: "Northern Illinois Huskies",
  NMST: "New Mexico State Aggies",
  NMSU: "New Mexico State Aggies",
  NU: "Northwestern Wildcats",
  NW: "Northwestern Wildcats",
  ODU: "Old Dominion Monarchs",
  OHIO: "Ohio Bobcats",
  OKST: "Oklahoma State Cowboys",
  ORE: "Oregon Ducks",
  ORST: "Oregon State Beavers",
  OSU: "Ohio State Buckeyes",
  OU: "Oklahoma Sooners",
  PITT: "Pittsburgh Panthers",
  PSU: "Penn State Nittany Lions",
  PUR: "Purdue Boilermakers",
  RICE: "Rice Owls",
  RUT: "Rutgers Scarlet Knights",
  RUTG: "Rutgers Scarlet Knights",
  SC: "South Carolina Gamecocks",
  SDSU: "San Diego State Aztecs",
  SHSU: "Sam Houston Bearkats",
  SJSU: "San José State Spartans",
  SMU: "SMU Mustangs",
  SOAL: "South Alabama Jaguars",
  STAN: "Stanford Cardinal",
  SYR: "Syracuse Orange",
  "TA&M": "Texas A&M Aggies",
  TAMU: "Texas A&M Aggies",
  TCU: "TCU Horned Frogs",
  TEM: "Temple Owls",
  TENN: "Tennessee Volunteers",
  TEX: "Texas Longhorns",
  TLSA: "Tulsa Golden Hurricane",
  TOL: "Toledo Rockets",
  TROY: "Troy Trojans",
  TTU: "Texas Tech Red Raiders",
  TUL: "Tulane Green Wave",
  TULN: "Tulane Green Wave",
  TXST: "Texas State Bobcats",
  UAB: "UAB Blazers",
  UCF: "UCF Knights",
  UCLA: "UCLA Bruins",
  UGA: "Georgia Bulldogs",
  UK: "Kentucky Wildcats",
  UL: "Louisiana Ragin' Cajuns",
  ULL: "Louisiana Ragin' Cajuns",
  ULM: "UL Monroe Warhawks",
  UNC: "North Carolina Tar Heels",
  UNLV: "UNLV Rebels",
  UNM: "New Mexico Lobos",
  UNT: "North Texas Mean Green",
  USA: "South Alabama Jaguars",
  USC: "USC Trojans",
  USF: "South Florida Bulls",
  USM: "Southern Miss Golden Eagles",
  USU: "Utah State Aggies",
  UTAH: "Utah Utes",
  UTEP: "UTEP Miners",
  UTSA: "UTSA Roadrunners",
  UVA: "Virginia Cavaliers",
  VAN: "Vanderbilt Commodores",
  VT: "Virginia Tech Hokies",
  WAKE: "Wake Forest Demon Deacons",
  WASH: "Washington Huskies",
  WCU: "Western Carolina Catamounts",
  WIS: "Wisconsin Badgers",
  WKU: "Western Kentucky Hilltoppers",
  WMU: "Western Michigan Broncos",
  WSU: "Washington State Cougars",
  WVU: "West Virginia Mountaineers",
  WYO: "Wyoming Cowboys",
};

/**
 * Tokens the odds adapter writes into games.home_team / games.away_team
 * that are a mascot slice rather than an abbreviation, with the schools
 * written as each. A logo must never be resolved from one of these: the
 * slice names a mascot, so it can belong to several schools and can
 * collide with a different school's real abbreviation.
 *
 * Slices that ARE the school's own ESPN abbreviation are excluded, because
 * the token does identify the school: ILL
 */
export const CFB_MASCOT_SLICE_TOKENS: ReadonlyArray<{
  readonly token: string;
  readonly teams: readonly string[];
}> = [
  { token: "49E", teams: ["Charlotte 49ers"] },
  { token: "AGG", teams: ["New Mexico State Aggies"] },
  { token: "AZT", teams: ["San Diego State Aztecs"] },
  { token: "BEA", teams: ["Cincinnati Bearcats","Missouri State Bears","Oregon State Beavers","Sam Houston Bearkats"] },
  { token: "BLA", teams: ["UAB Blazers"] },
  { token: "BOB", teams: ["Ohio Bobcats","Texas State Bobcats"] },
  { token: "BOI", teams: ["Purdue Boilermakers"] },
  { token: "BRO", teams: ["Western Michigan Broncos"] },
  { token: "BUL", teams: ["Buffalo Bulls","Fresno State Bulldogs","Louisiana Tech Bulldogs","South Florida Bulls"] },
  { token: "CAJ", teams: ["Louisiana Ragin' Cajuns"] },
  { token: "CAR", teams: ["Ball State Cardinals"] },
  { token: "CAV", teams: ["Virginia Cavaliers"] },
  { token: "CHA", teams: ["Coastal Carolina Chanticleers"] },
  { token: "CHI", teams: ["Central Michigan Chippewas"] },
  { token: "COM", teams: ["Vanderbilt Commodores"] },
  { token: "COR", teams: ["Nebraska Cornhuskers"] },
  { token: "COU", teams: ["BYU Cougars","Houston Cougars","Washington State Cougars"] },
  { token: "COW", teams: ["Wyoming Cowboys"] },
  { token: "DEA", teams: ["Wake Forest Demon Deacons"] },
  { token: "DUK", teams: ["James Madison Dukes"] },
  { token: "EAG", teams: ["Boston College Eagles","Eastern Michigan Eagles","Georgia Southern Eagles","Southern Miss Golden Eagles"] },
  { token: "FAL", teams: ["Bowling Green Falcons"] },
  { token: "FLA", teams: ["Kent State Golden Flashes","Liberty Flames"] },
  { token: "GAM", teams: ["Jacksonville State Gamecocks","South Carolina Gamecocks"] },
  { token: "GAT", teams: ["Florida Gators"] },
  { token: "GOP", teams: ["Minnesota Golden Gophers"] },
  { token: "GRE", teams: ["North Texas Mean Green"] },
  { token: "HEN", teams: ["Delaware Blue Hens"] },
  { token: "HER", teams: ["Marshall Thundering Herd"] },
  { token: "HIL", teams: ["Western Kentucky Hilltoppers"] },
  { token: "HOO", teams: ["Indiana Hoosiers"] },
  { token: "HUR", teams: ["Miami Hurricanes","Tulsa Golden Hurricane"] },
  { token: "HUS", teams: ["Northern Illinois Huskies","UConn Huskies"] },
  { token: "JAC", teams: ["Georgia Tech Yellow Jackets"] },
  { token: "JAG", teams: ["South Alabama Jaguars"] },
  { token: "JAY", teams: ["Kansas Jayhawks"] },
  { token: "KNI", teams: ["Rutgers Scarlet Knights","UCF Knights"] },
  { token: "LOB", teams: ["New Mexico Lobos"] },
  { token: "MIN", teams: ["Massachusetts Minutemen","UTEP Miners"] },
  { token: "MON", teams: ["Old Dominion Monarchs"] },
  { token: "MOU", teams: ["App State Mountaineers"] },
  { token: "MUS", teams: ["SMU Mustangs"] },
  { token: "ORA", teams: ["Syracuse Orange"] },
  { token: "OWL", teams: ["Florida Atlantic Owls","Kennesaw State Owls","Rice Owls","Temple Owls"] },
  { token: "PAC", teams: ["Nevada Wolf Pack"] },
  { token: "PAN", teams: ["Florida International Panthers","Georgia State Panthers"] },
  { token: "PIR", teams: ["East Carolina Pirates"] },
  { token: "RAI", teams: ["Middle Tennessee Blue Raiders","Texas Tech Red Raiders"] },
  { token: "RAM", teams: ["Colorado State Rams"] },
  { token: "REB", teams: ["UNLV Rebels"] },
  { token: "RED", teams: ["Miami (OH) RedHawks"] },
  { token: "ROA", teams: ["UTSA Roadrunners"] },
  { token: "ROC", teams: ["Toledo Rockets"] },
  { token: "SPA", teams: ["San José State Spartans"] },
  { token: "TER", teams: ["Maryland Terrapins"] },
  { token: "TIG", teams: ["Memphis Tigers"] },
  { token: "TRO", teams: ["Troy Trojans"] },
  { token: "WAR", teams: ["Hawai'i Rainbow Warriors","UL Monroe Warhawks"] },
  { token: "WAV", teams: ["Tulane Green Wave"] },
  { token: "WIL", teams: ["Kentucky Wildcats","Northwestern Wildcats"] },
  { token: "WOL", teams: ["Arkansas State Red Wolves"] },
  { token: "ZIP", teams: ["Akron Zips"] },
];

/**
 * Required keys ESPN's FBS data could not resolve. Listed, never guessed —
 * a team here renders the abbreviation badge, which is the honest outcome.
 */
export const CFB_LOGO_GAPS: ReadonlyArray<{
  readonly abbr: string;
  readonly name: string;
  readonly source: string;
  readonly reason: string;
}> = [
  {"abbr":"WST","source":"manifest","name":"Wichita State","reason":"no FBS team matched this abbreviation or name"},
];
