/**
 * GENERATED FILE — do not edit by hand.
 *   npm run generate:cfb-logos
 *
 * The CFB half of game resolution, from ESPN's own team data.
 *   season        2025
 *   generated     2026-10-09
 *   teams         137
 *   lookup keys   588
 *   ambiguous stored tokens 16
 *
 * `stored` is the token the odds adapter writes into games.home_team and
 * games.away_team for that school: shortCode(<The Odds API team name>).
 * For the schools NAME_TO_CODE covers it is the mapped code; for the rest
 * it is the first three letters of the mascot word, which is what
 * shortCode falls back to. The generator refuses to write this file unless
 * the odds feed and ESPN agree on the mascot word for every NAME_TO_CODE
 * name it can check, because that agreement is the only evidence the
 * derivation is right for the schools no odds name is on record for.
 *
 * Nothing here is keyed off an abbreviation alone: identity is ESPN's
 * numeric team id, and a key two schools would both claim is dropped
 * rather than pointed at one of them.
 */

export interface CfbEspnTeam {
  /** ESPN displayName, verbatim. */
  readonly name: string;
  /** ESPN's own abbreviation for this team. */
  readonly abbr: string;
  /** The token the odds adapter stores in games.home_team / games.away_team. */
  readonly stored: string;
  /** In ESPN's FBS group 80 for the generated season. */
  readonly fbs: boolean;
}

/** ESPN numeric team id -> that team's identity and stored token. */
export const CFB_ESPN_TEAM_BY_ID: Readonly<Record<string, CfbEspnTeam>> = {
  "2": { name: "Auburn Tigers", abbr: "AUB", stored: "AUB", fbs: true },
  "5": { name: "UAB Blazers", abbr: "UAB", stored: "BLA", fbs: true },
  "6": { name: "South Alabama Jaguars", abbr: "USA", stored: "JAG", fbs: true },
  "8": { name: "Arkansas Razorbacks", abbr: "ARK", stored: "ARK", fbs: true },
  "9": { name: "Arizona State Sun Devils", abbr: "ASU", stored: "ASU", fbs: true },
  "12": { name: "Arizona Wildcats", abbr: "ARIZ", stored: "ARIZ", fbs: true },
  "21": { name: "San Diego State Aztecs", abbr: "SDSU", stored: "AZT", fbs: true },
  "23": { name: "San José State Spartans", abbr: "SJSU", stored: "SPA", fbs: true },
  "24": { name: "Stanford Cardinal", abbr: "STAN", stored: "STAN", fbs: true },
  "25": { name: "California Golden Bears", abbr: "CAL", stored: "CAL", fbs: true },
  "26": { name: "UCLA Bruins", abbr: "UCLA", stored: "UCLA", fbs: true },
  "30": { name: "USC Trojans", abbr: "USC", stored: "USC", fbs: true },
  "36": { name: "Colorado State Rams", abbr: "CSU", stored: "RAM", fbs: true },
  "38": { name: "Colorado Buffaloes", abbr: "COLO", stored: "COLO", fbs: true },
  "41": { name: "UConn Huskies", abbr: "CONN", stored: "HUS", fbs: true },
  "48": { name: "Delaware Blue Hens", abbr: "DEL", stored: "HEN", fbs: true },
  "52": { name: "Florida State Seminoles", abbr: "FSU", stored: "FSU", fbs: true },
  "55": { name: "Jacksonville State Gamecocks", abbr: "JXST", stored: "GAM", fbs: true },
  "57": { name: "Florida Gators", abbr: "FLA", stored: "GAT", fbs: true },
  "58": { name: "South Florida Bulls", abbr: "USF", stored: "BUL", fbs: true },
  "59": { name: "Georgia Tech Yellow Jackets", abbr: "GT", stored: "JAC", fbs: true },
  "61": { name: "Georgia Bulldogs", abbr: "UGA", stored: "UGA", fbs: true },
  "62": { name: "Hawai'i Rainbow Warriors", abbr: "HAW", stored: "WAR", fbs: true },
  "66": { name: "Iowa State Cyclones", abbr: "ISU", stored: "ISU", fbs: true },
  "68": { name: "Boise State Broncos", abbr: "BOIS", stored: "BSU", fbs: true },
  "77": { name: "Northwestern Wildcats", abbr: "NU", stored: "WIL", fbs: true },
  "84": { name: "Indiana Hoosiers", abbr: "IU", stored: "HOO", fbs: true },
  "87": { name: "Notre Dame Fighting Irish", abbr: "ND", stored: "ND", fbs: true },
  "96": { name: "Kentucky Wildcats", abbr: "UK", stored: "WIL", fbs: true },
  "97": { name: "Louisville Cardinals", abbr: "LOU", stored: "LOU", fbs: true },
  "98": { name: "Western Kentucky Hilltoppers", abbr: "WKU", stored: "HIL", fbs: true },
  "99": { name: "LSU Tigers", abbr: "LSU", stored: "LSU", fbs: true },
  "103": { name: "Boston College Eagles", abbr: "BC", stored: "EAG", fbs: true },
  "113": { name: "Massachusetts Minutemen", abbr: "MASS", stored: "MIN", fbs: true },
  "120": { name: "Maryland Terrapins", abbr: "MD", stored: "TER", fbs: true },
  "127": { name: "Michigan State Spartans", abbr: "MSU", stored: "MSU", fbs: true },
  "130": { name: "Michigan Wolverines", abbr: "MICH", stored: "MICH", fbs: true },
  "135": { name: "Minnesota Golden Gophers", abbr: "MINN", stored: "GOP", fbs: true },
  "142": { name: "Missouri Tigers", abbr: "MIZ", stored: "MIZ", fbs: true },
  "145": { name: "Ole Miss Rebels", abbr: "MISS", stored: "MISS", fbs: true },
  "150": { name: "Duke Blue Devils", abbr: "DUKE", stored: "DUKE", fbs: true },
  "151": { name: "East Carolina Pirates", abbr: "ECU", stored: "PIR", fbs: true },
  "152": { name: "NC State Wolfpack", abbr: "NCSU", stored: "NCST", fbs: true },
  "153": { name: "North Carolina Tar Heels", abbr: "UNC", stored: "UNC", fbs: true },
  "154": { name: "Wake Forest Demon Deacons", abbr: "WAKE", stored: "DEA", fbs: true },
  "158": { name: "Nebraska Cornhuskers", abbr: "NEB", stored: "COR", fbs: true },
  "164": { name: "Rutgers Scarlet Knights", abbr: "RUTG", stored: "KNI", fbs: true },
  "166": { name: "New Mexico State Aggies", abbr: "NMSU", stored: "AGG", fbs: true },
  "167": { name: "New Mexico Lobos", abbr: "UNM", stored: "LOB", fbs: true },
  "183": { name: "Syracuse Orange", abbr: "SYR", stored: "ORA", fbs: true },
  "189": { name: "Bowling Green Falcons", abbr: "BGSU", stored: "FAL", fbs: true },
  "193": { name: "Miami (OH) RedHawks", abbr: "M-OH", stored: "RED", fbs: true },
  "194": { name: "Ohio State Buckeyes", abbr: "OSU", stored: "OSU", fbs: true },
  "195": { name: "Ohio Bobcats", abbr: "OHIO", stored: "BOB", fbs: true },
  "197": { name: "Oklahoma State Cowboys", abbr: "OKST", stored: "OKST", fbs: true },
  "201": { name: "Oklahoma Sooners", abbr: "OU", stored: "OU", fbs: true },
  "202": { name: "Tulsa Golden Hurricane", abbr: "TLSA", stored: "HUR", fbs: true },
  "204": { name: "Oregon State Beavers", abbr: "ORST", stored: "BEA", fbs: true },
  "213": { name: "Penn State Nittany Lions", abbr: "PSU", stored: "PSU", fbs: true },
  "218": { name: "Temple Owls", abbr: "TEM", stored: "OWL", fbs: true },
  "221": { name: "Pittsburgh Panthers", abbr: "PITT", stored: "PITT", fbs: true },
  "228": { name: "Clemson Tigers", abbr: "CLEM", stored: "CLEM", fbs: true },
  "235": { name: "Memphis Tigers", abbr: "MEM", stored: "TIG", fbs: true },
  "238": { name: "Vanderbilt Commodores", abbr: "VAN", stored: "COM", fbs: true },
  "239": { name: "Baylor Bears", abbr: "BAY", stored: "BAY", fbs: true },
  "242": { name: "Rice Owls", abbr: "RICE", stored: "OWL", fbs: true },
  "245": { name: "Texas A&M Aggies", abbr: "TA&M", stored: "TAMU", fbs: true },
  "248": { name: "Houston Cougars", abbr: "HOU", stored: "COU", fbs: true },
  "249": { name: "North Texas Mean Green", abbr: "UNT", stored: "GRE", fbs: true },
  "251": { name: "Texas Longhorns", abbr: "TEX", stored: "TEX", fbs: true },
  "252": { name: "BYU Cougars", abbr: "BYU", stored: "COU", fbs: true },
  "254": { name: "Utah Utes", abbr: "UTAH", stored: "UTAH", fbs: true },
  "256": { name: "James Madison Dukes", abbr: "JMU", stored: "DUK", fbs: true },
  "258": { name: "Virginia Cavaliers", abbr: "UVA", stored: "CAV", fbs: true },
  "259": { name: "Virginia Tech Hokies", abbr: "VT", stored: "VT", fbs: true },
  "264": { name: "Washington Huskies", abbr: "WASH", stored: "WASH", fbs: true },
  "265": { name: "Washington State Cougars", abbr: "WSU", stored: "COU", fbs: true },
  "275": { name: "Wisconsin Badgers", abbr: "WIS", stored: "WIS", fbs: true },
  "276": { name: "Marshall Thundering Herd", abbr: "MRSH", stored: "HER", fbs: true },
  "277": { name: "West Virginia Mountaineers", abbr: "WVU", stored: "WVU", fbs: true },
  "278": { name: "Fresno State Bulldogs", abbr: "FRES", stored: "BUL", fbs: true },
  "290": { name: "Georgia Southern Eagles", abbr: "GASO", stored: "EAG", fbs: true },
  "295": { name: "Old Dominion Monarchs", abbr: "ODU", stored: "MON", fbs: true },
  "309": { name: "Louisiana Ragin' Cajuns", abbr: "UL", stored: "CAJ", fbs: true },
  "324": { name: "Coastal Carolina Chanticleers", abbr: "CCU", stored: "CHA", fbs: true },
  "326": { name: "Texas State Bobcats", abbr: "TXST", stored: "BOB", fbs: true },
  "328": { name: "Utah State Aggies", abbr: "USU", stored: "USU", fbs: true },
  "333": { name: "Alabama Crimson Tide", abbr: "ALA", stored: "ALA", fbs: true },
  "338": { name: "Kennesaw State Owls", abbr: "KENN", stored: "OWL", fbs: true },
  "344": { name: "Mississippi State Bulldogs", abbr: "MSST", stored: "MSST", fbs: true },
  "349": { name: "Army Black Knights", abbr: "ARMY", stored: "ARMY", fbs: true },
  "356": { name: "Illinois Fighting Illini", abbr: "ILL", stored: "ILL", fbs: true },
  "2005": { name: "Air Force Falcons", abbr: "AF", stored: "AFA", fbs: true },
  "2006": { name: "Akron Zips", abbr: "AKR", stored: "ZIP", fbs: true },
  "2026": { name: "App State Mountaineers", abbr: "APP", stored: "MOU", fbs: true },
  "2032": { name: "Arkansas State Red Wolves", abbr: "ARST", stored: "WOL", fbs: true },
  "2050": { name: "Ball State Cardinals", abbr: "BALL", stored: "CAR", fbs: true },
  "2084": { name: "Buffalo Bulls", abbr: "BUF", stored: "BUL", fbs: true },
  "2116": { name: "UCF Knights", abbr: "UCF", stored: "KNI", fbs: true },
  "2117": { name: "Central Michigan Chippewas", abbr: "CMU", stored: "CHI", fbs: true },
  "2132": { name: "Cincinnati Bearcats", abbr: "CIN", stored: "BEA", fbs: true },
  "2199": { name: "Eastern Michigan Eagles", abbr: "EMU", stored: "EAG", fbs: true },
  "2226": { name: "Florida Atlantic Owls", abbr: "FAU", stored: "OWL", fbs: true },
  "2229": { name: "Florida International Panthers", abbr: "FIU", stored: "PAN", fbs: true },
  "2247": { name: "Georgia State Panthers", abbr: "GAST", stored: "PAN", fbs: true },
  "2294": { name: "Iowa Hawkeyes", abbr: "IOWA", stored: "IOWA", fbs: true },
  "2305": { name: "Kansas Jayhawks", abbr: "KU", stored: "JAY", fbs: true },
  "2306": { name: "Kansas State Wildcats", abbr: "KSU", stored: "KSU", fbs: true },
  "2309": { name: "Kent State Golden Flashes", abbr: "KENT", stored: "FLA", fbs: true },
  "2335": { name: "Liberty Flames", abbr: "LIB", stored: "FLA", fbs: true },
  "2348": { name: "Louisiana Tech Bulldogs", abbr: "LT", stored: "BUL", fbs: true },
  "2390": { name: "Miami Hurricanes", abbr: "MIA", stored: "HUR", fbs: true },
  "2393": { name: "Middle Tennessee Blue Raiders", abbr: "MTSU", stored: "RAI", fbs: true },
  "2426": { name: "Navy Midshipmen", abbr: "NAVY", stored: "NAVY", fbs: true },
  "2429": { name: "Charlotte 49ers", abbr: "CLT", stored: "49E", fbs: true },
  "2433": { name: "UL Monroe Warhawks", abbr: "ULM", stored: "WAR", fbs: true },
  "2439": { name: "UNLV Rebels", abbr: "UNLV", stored: "REB", fbs: true },
  "2440": { name: "Nevada Wolf Pack", abbr: "NEV", stored: "PAC", fbs: true },
  "2459": { name: "Northern Illinois Huskies", abbr: "NIU", stored: "HUS", fbs: true },
  "2483": { name: "Oregon Ducks", abbr: "ORE", stored: "ORE", fbs: true },
  "2509": { name: "Purdue Boilermakers", abbr: "PUR", stored: "BOI", fbs: true },
  "2534": { name: "Sam Houston Bearkats", abbr: "SHSU", stored: "BEA", fbs: true },
  "2567": { name: "SMU Mustangs", abbr: "SMU", stored: "MUS", fbs: true },
  "2572": { name: "Southern Miss Golden Eagles", abbr: "USM", stored: "EAG", fbs: true },
  "2579": { name: "South Carolina Gamecocks", abbr: "SC", stored: "GAM", fbs: true },
  "2623": { name: "Missouri State Bears", abbr: "MOST", stored: "BEA", fbs: true },
  "2628": { name: "TCU Horned Frogs", abbr: "TCU", stored: "TCU", fbs: true },
  "2633": { name: "Tennessee Volunteers", abbr: "TENN", stored: "TENN", fbs: true },
  "2636": { name: "UTSA Roadrunners", abbr: "UTSA", stored: "ROA", fbs: true },
  "2638": { name: "UTEP Miners", abbr: "UTEP", stored: "MIN", fbs: true },
  "2641": { name: "Texas Tech Red Raiders", abbr: "TTU", stored: "RAI", fbs: true },
  "2649": { name: "Toledo Rockets", abbr: "TOL", stored: "ROC", fbs: true },
  "2653": { name: "Troy Trojans", abbr: "TROY", stored: "TRO", fbs: true },
  "2655": { name: "Tulane Green Wave", abbr: "TULN", stored: "WAV", fbs: true },
  "2711": { name: "Western Michigan Broncos", abbr: "WMU", stored: "BRO", fbs: true },
  "2717": { name: "Western Carolina Catamounts", abbr: "WCU", stored: "CAT", fbs: false },
  "2751": { name: "Wyoming Cowboys", abbr: "WYO", stored: "COW", fbs: true },
};

/**
 * Lookup key -> ESPN numeric team id. Uppercase keys are abbreviation
 * spellings (ESPN's, the school manifest's, the odds adapter's, and each
 * team's stored token where it is unique); lowercase keys are display
 * names, locations, short names and slugs with every non-alphanumeric
 * character stripped.
 */
export const CFB_TEAM_KEY_TO_ESPN_ID: Readonly<Record<string, string>> = {
  "49E": "2429",
  "49ers": "2429",
  AF: "2005",
  AFA: "2005",
  AGG: "166",
  AKR: "2006",
  ALA: "333",
  APP: "2026",
  ARIZ: "12",
  ARK: "8",
  ARMY: "349",
  ARST: "2032",
  ASU: "9",
  AUB: "2",
  AZT: "21",
  BALL: "2050",
  BAY: "239",
  BC: "103",
  BGSU: "189",
  BLA: "5",
  BOI: "2509",
  BOIS: "68",
  BRO: "2711",
  BSU: "68",
  BUF: "2084",
  BUFF: "2084",
  BYU: "252",
  CAJ: "309",
  CAL: "25",
  CAR: "2050",
  CAT: "2717",
  CAV: "258",
  CCU: "324",
  CHA: "324",
  CHI: "2117",
  CIN: "2132",
  CLEM: "228",
  CLT: "2429",
  CMU: "2117",
  COL: "38",
  COLO: "38",
  COM: "238",
  CONN: "41",
  COR: "158",
  COW: "2751",
  CSU: "36",
  DEA: "154",
  DEL: "48",
  DUK: "256",
  DUKE: "150",
  ECU: "151",
  EMU: "2199",
  FAL: "189",
  FAU: "2226",
  FINT: "2229",
  FIU: "2229",
  FLA: "57",
  FRES: "278",
  FSU: "52",
  GASO: "290",
  GAST: "2247",
  GAT: "57",
  GOP: "135",
  GRE: "249",
  GT: "59",
  HAW: "62",
  HEN: "48",
  HER: "276",
  HIL: "98",
  HOO: "84",
  HOU: "248",
  ILL: "356",
  IND: "84",
  IOWA: "2294",
  ISU: "66",
  IU: "84",
  JAC: "59",
  JAG: "6",
  JAY: "2305",
  JMU: "256",
  JSU: "55",
  JXST: "55",
  KENN: "338",
  KENT: "2309",
  KSU: "2306",
  KU: "2305",
  LATECH: "2348",
  LIB: "2335",
  LOB: "167",
  LOU: "97",
  LSU: "99",
  LT: "2348",
  "M-OH": "193",
  MASS: "113",
  MD: "120",
  MEM: "235",
  MIA: "2390",
  MICH: "130",
  MINN: "135",
  MIOH: "193",
  MISS: "145",
  MIZ: "142",
  MON: "295",
  MOST: "2623",
  MOU: "2026",
  MRSH: "276",
  MSST: "344",
  MSU: "127",
  MTSU: "2393",
  MUS: "2567",
  NAVY: "2426",
  NCST: "152",
  NCSU: "152",
  ND: "87",
  NEB: "158",
  NEV: "2440",
  NIU: "2459",
  NMST: "166",
  NMSU: "166",
  NU: "77",
  NW: "77",
  ODU: "295",
  OHIO: "195",
  OKST: "197",
  ORA: "183",
  ORE: "2483",
  ORST: "204",
  OSU: "194",
  OU: "201",
  PAC: "2440",
  PIR: "151",
  PITT: "221",
  PSU: "213",
  PUR: "2509",
  RAM: "36",
  REB: "2439",
  RED: "193",
  RICE: "242",
  ROA: "2636",
  ROC: "2649",
  RUT: "164",
  RUTG: "164",
  SC: "2579",
  SDSU: "21",
  SHSU: "2534",
  SJSU: "23",
  SMU: "2567",
  SOAL: "6",
  SPA: "23",
  STAN: "24",
  SYR: "183",
  "TA&M": "245",
  TAMU: "245",
  TCU: "2628",
  TEM: "218",
  TENN: "2633",
  TER: "120",
  TEX: "251",
  TIG: "235",
  TLSA: "202",
  TOL: "2649",
  TRO: "2653",
  TROY: "2653",
  TTU: "2641",
  TUL: "2655",
  TULN: "2655",
  TXST: "326",
  UAB: "5",
  UCF: "2116",
  UCLA: "26",
  UGA: "61",
  UK: "96",
  UL: "309",
  ULL: "309",
  ULM: "2433",
  UNC: "153",
  UNLV: "2439",
  UNM: "167",
  UNT: "249",
  USA: "6",
  USC: "30",
  USF: "58",
  USM: "2572",
  USU: "328",
  UTAH: "254",
  UTEP: "2638",
  UTSA: "2636",
  UVA: "258",
  VAN: "238",
  VT: "259",
  WAKE: "154",
  WASH: "264",
  WAV: "2655",
  WCU: "2717",
  WIS: "275",
  WKU: "98",
  WMU: "2711",
  WOL: "2032",
  WSU: "265",
  WVU: "277",
  WYO: "2751",
  ZIP: "2006",
  "airforce": "2005",
  "airforcefalcons": "2005",
  "akron": "2006",
  "akronzips": "2006",
  "alabama": "333",
  "alabamacrimsontide": "333",
  "appstate": "2026",
  "appstatemountaineers": "2026",
  "arizona": "12",
  "arizonast": "9",
  "arizonastate": "9",
  "arizonastatesundevils": "9",
  "arizonawildcats": "12",
  "arkansas": "8",
  "arkansasrazorbacks": "8",
  "arkansasst": "2032",
  "arkansasstate": "2032",
  "arkansasstateredwolves": "2032",
  "army": "349",
  "armyblackknights": "349",
  "auburn": "2",
  "auburntigers": "2",
  "aztecs": "21",
  "badgers": "275",
  "ballstate": "2050",
  "ballstatecardinals": "2050",
  "baylor": "239",
  "baylorbears": "239",
  "bearcats": "2132",
  "bearkats": "2534",
  "beavers": "204",
  "blackknights": "349",
  "blazers": "5",
  "bluedevils": "150",
  "bluehens": "48",
  "blueraiders": "2393",
  "boilermakers": "2509",
  "boisest": "68",
  "boisestate": "68",
  "boisestatebroncos": "68",
  "bostoncollege": "103",
  "bostoncollegeeagles": "103",
  "bowlinggreen": "189",
  "bowlinggreenfalcons": "189",
  "bruins": "26",
  "buckeyes": "194",
  "buffalo": "2084",
  "buffalobulls": "2084",
  "buffaloes": "38",
  "byu": "252",
  "byucougars": "252",
  "california": "25",
  "californiagoldenbears": "25",
  "cardinal": "24",
  "catamounts": "2717",
  "cavaliers": "258",
  "centralmichigan": "2117",
  "centralmichiganchippewas": "2117",
  "chanticleers": "324",
  "charlotte": "2429",
  "charlotte49ers": "2429",
  "chippewas": "2117",
  "cincinnati": "2132",
  "cincinnatibearcats": "2132",
  "clemson": "228",
  "clemsontigers": "228",
  "cmichigan": "2117",
  "coastal": "324",
  "coastalcarolina": "324",
  "coastalcarolinachanticleers": "324",
  "colorado": "38",
  "coloradobuffaloes": "38",
  "coloradost": "36",
  "coloradostate": "36",
  "coloradostaterams": "36",
  "commodores": "238",
  "cornhuskers": "158",
  "crimsontide": "333",
  "cyclones": "66",
  "delaware": "48",
  "delawarebluehens": "48",
  "demondeacons": "154",
  "ducks": "2483",
  "duke": "150",
  "dukebluedevils": "150",
  "dukes": "256",
  "eastcarolina": "151",
  "eastcarolinapirates": "151",
  "easternmichigan": "2199",
  "easternmichiganeagles": "2199",
  "emichigan": "2199",
  "fau": "2226",
  "fightingillini": "356",
  "fightingirish": "87",
  "fiu": "2229",
  "flames": "2335",
  "florida": "57",
  "floridaatlantic": "2226",
  "floridaatlanticowls": "2226",
  "floridagators": "57",
  "floridainternational": "2229",
  "floridainternationalpanthers": "2229",
  "floridast": "52",
  "floridastate": "52",
  "floridastateseminoles": "52",
  "fresnost": "278",
  "fresnostate": "278",
  "fresnostatebulldogs": "278",
  "gasouthern": "290",
  "gators": "57",
  "georgia": "61",
  "georgiabulldogs": "61",
  "georgiasouthern": "290",
  "georgiasoutherneagles": "290",
  "georgiast": "2247",
  "georgiastate": "2247",
  "georgiastatepanthers": "2247",
  "georgiatech": "59",
  "georgiatechyellowjackets": "59",
  "goldenbears": "25",
  "goldeneagles": "2572",
  "goldenflashes": "2309",
  "goldengophers": "135",
  "goldenhurricane": "202",
  "greenwave": "2655",
  "hawaii": "62",
  "hawaiirainbowwarriors": "62",
  "hawkeyes": "2294",
  "hilltoppers": "98",
  "hokies": "259",
  "hoosiers": "84",
  "hornedfrogs": "2628",
  "houston": "248",
  "houstoncougars": "248",
  "hurricanes": "2390",
  "illinois": "356",
  "illinoisfightingillini": "356",
  "indiana": "84",
  "indianahoosiers": "84",
  "iowa": "2294",
  "iowahawkeyes": "2294",
  "iowastate": "66",
  "iowastatecyclones": "66",
  "jacksonvillestate": "55",
  "jacksonvillestategamecocks": "55",
  "jaguars": "6",
  "jamesmadison": "256",
  "jamesmadisondukes": "256",
  "jaxstate": "55",
  "jayhawks": "2305",
  "kansas": "2305",
  "kansasjayhawks": "2305",
  "kansasst": "2306",
  "kansasstate": "2306",
  "kansasstatewildcats": "2306",
  "kennesawst": "338",
  "kennesawstate": "338",
  "kennesawstateowls": "338",
  "kentstate": "2309",
  "kentstategoldenflashes": "2309",
  "kentucky": "96",
  "kentuckywildcats": "96",
  "knights": "2116",
  "liberty": "2335",
  "libertyflames": "2335",
  "lobos": "167",
  "longhorns": "251",
  "louisiana": "309",
  "louisianaragincajuns": "309",
  "louisianatech": "2348",
  "louisianatechbulldogs": "2348",
  "louisville": "97",
  "louisvillecardinals": "97",
  "lsu": "99",
  "lsutigers": "99",
  "marshall": "276",
  "marshallthunderingherd": "276",
  "maryland": "120",
  "marylandterrapins": "120",
  "massachusetts": "113",
  "massachusettsminutemen": "113",
  "meangreen": "249",
  "memphis": "235",
  "memphistigers": "235",
  "miami": "2390",
  "miamihurricanes": "2390",
  "miamioh": "193",
  "miamiohredhawks": "193",
  "michigan": "130",
  "michiganst": "127",
  "michiganstate": "127",
  "michiganstatespartans": "127",
  "michiganwolverines": "130",
  "middletennessee": "2393",
  "middletennesseeblueraiders": "2393",
  "midshipmen": "2426",
  "miners": "2638",
  "minnesota": "135",
  "minnesotagoldengophers": "135",
  "minutemen": "113",
  "mississippist": "344",
  "mississippistate": "344",
  "mississippistatebulldogs": "344",
  "missouri": "142",
  "missourist": "2623",
  "missouristate": "2623",
  "missouristatebears": "2623",
  "missouritigers": "142",
  "monarchs": "295",
  "mtsu": "2393",
  "mustangs": "2567",
  "navy": "2426",
  "navymidshipmen": "2426",
  "ncstate": "152",
  "ncstatewolfpack": "152",
  "nebraska": "158",
  "nebraskacornhuskers": "158",
  "nevada": "2440",
  "nevadawolfpack": "2440",
  "newmexico": "167",
  "newmexicolobos": "167",
  "newmexicost": "166",
  "newmexicostate": "166",
  "newmexicostateaggies": "166",
  "nillinois": "2459",
  "nittanylions": "213",
  "northcarolina": "153",
  "northcarolinatarheels": "153",
  "northernillinois": "2459",
  "northernillinoishuskies": "2459",
  "northtexas": "249",
  "northtexasmeangreen": "249",
  "northwestern": "77",
  "northwesternwildcats": "77",
  "notredame": "87",
  "notredamefightingirish": "87",
  "ohio": "195",
  "ohiobobcats": "195",
  "ohiostate": "194",
  "ohiostatebuckeyes": "194",
  "oklahoma": "201",
  "oklahomasooners": "201",
  "oklahomast": "197",
  "oklahomastate": "197",
  "oklahomastatecowboys": "197",
  "olddominion": "295",
  "olddominionmonarchs": "295",
  "olemiss": "145",
  "olemissrebels": "145",
  "orange": "183",
  "oregon": "2483",
  "oregonducks": "2483",
  "oregonst": "204",
  "oregonstate": "204",
  "oregonstatebeavers": "204",
  "pennstate": "213",
  "pennstatenittanylions": "213",
  "pirates": "151",
  "pitt": "221",
  "pittsburgh": "221",
  "pittsburghpanthers": "221",
  "purdue": "2509",
  "purdueboilermakers": "2509",
  "ragincajuns": "309",
  "rainbowwarriors": "62",
  "rams": "36",
  "razorbacks": "8",
  "redhawks": "193",
  "redraiders": "2641",
  "redwolves": "2032",
  "rice": "242",
  "riceowls": "242",
  "roadrunners": "2636",
  "rockets": "2649",
  "rutgers": "164",
  "rutgersscarletknights": "164",
  "samhouston": "2534",
  "samhoustonbearkats": "2534",
  "sandiegost": "21",
  "sandiegostate": "21",
  "sandiegostateaztecs": "21",
  "sanjosestatespartans": "23",
  "sanjosst": "23",
  "sanjosstate": "23",
  "sanjosstatespartans": "23",
  "scarletknights": "164",
  "seminoles": "52",
  "smu": "2567",
  "smumustangs": "2567",
  "sooners": "201",
  "southalabama": "6",
  "southalabamajaguars": "6",
  "southcarolina": "2579",
  "southcarolinagamecocks": "2579",
  "southernmiss": "2572",
  "southernmissgoldeneagles": "2572",
  "southflorida": "58",
  "southfloridabulls": "58",
  "stanford": "24",
  "stanfordcardinal": "24",
  "sundevils": "9",
  "syracuse": "183",
  "syracuseorange": "183",
  "tarheels": "153",
  "tcu": "2628",
  "tcuhornedfrogs": "2628",
  "temple": "218",
  "templeowls": "218",
  "tennessee": "2633",
  "tennesseevolunteers": "2633",
  "terrapins": "120",
  "texas": "251",
  "texasam": "245",
  "texasamaggies": "245",
  "texaslonghorns": "251",
  "texasst": "326",
  "texasstate": "326",
  "texasstatebobcats": "326",
  "texastech": "2641",
  "texastechredraiders": "2641",
  "thunderingherd": "276",
  "toledo": "2649",
  "toledorockets": "2649",
  "troy": "2653",
  "troytrojans": "2653",
  "tulane": "2655",
  "tulanegreenwave": "2655",
  "tulsa": "202",
  "tulsagoldenhurricane": "202",
  "uab": "5",
  "uabblazers": "5",
  "ucf": "2116",
  "ucfknights": "2116",
  "ucla": "26",
  "uclabruins": "26",
  "uconn": "41",
  "uconnhuskies": "41",
  "ulmonroe": "2433",
  "ulmonroewarhawks": "2433",
  "umass": "113",
  "unlv": "2439",
  "unlvrebels": "2439",
  "usc": "30",
  "usctrojans": "30",
  "utah": "254",
  "utahstate": "328",
  "utahstateaggies": "328",
  "utahutes": "254",
  "utep": "2638",
  "utepminers": "2638",
  "utes": "254",
  "utsa": "2636",
  "utsaroadrunners": "2636",
  "vanderbilt": "238",
  "vanderbiltcommodores": "238",
  "virginia": "258",
  "virginiacavaliers": "258",
  "virginiatech": "259",
  "virginiatechhokies": "259",
  "volunteers": "2633",
  "wakeforest": "154",
  "wakeforestdemondeacons": "154",
  "warhawks": "2433",
  "washington": "264",
  "washingtonhuskies": "264",
  "washingtonst": "265",
  "washingtonstate": "265",
  "washingtonstatecougars": "265",
  "wcarolina": "2717",
  "westerncarolina": "2717",
  "westerncarolinacatamounts": "2717",
  "westernkentucky": "98",
  "westernkentuckyhilltoppers": "98",
  "westernky": "98",
  "westernmichigan": "2711",
  "westernmichiganbroncos": "2711",
  "westvirginia": "277",
  "westvirginiamountaineers": "277",
  "wisconsin": "275",
  "wisconsinbadgers": "275",
  "wmichigan": "2711",
  "wolverines": "130",
  "wyoming": "2751",
  "wyomingcowboys": "2751",
  "yellowjackets": "59",
  "zips": "2006",
};

/**
 * Stored tokens more than one school would be written as, with the schools
 * behind each. These are still used to widen a lookup — dropping them would
 * cost real matches — but a widened lookup that resolves to more than one
 * games row is refused rather than guessed.
 */
export const CFB_AMBIGUOUS_STORED_TOKENS: ReadonlyArray<{
  readonly token: string;
  readonly teams: readonly string[];
}> = [
  { token: "BEA", teams: ["Cincinnati Bearcats","Missouri State Bears","Oregon State Beavers","Sam Houston Bearkats"] },
  { token: "BOB", teams: ["Ohio Bobcats","Texas State Bobcats"] },
  { token: "BUL", teams: ["Buffalo Bulls","Fresno State Bulldogs","Louisiana Tech Bulldogs","South Florida Bulls"] },
  { token: "COU", teams: ["BYU Cougars","Houston Cougars","Washington State Cougars"] },
  { token: "EAG", teams: ["Boston College Eagles","Eastern Michigan Eagles","Georgia Southern Eagles","Southern Miss Golden Eagles"] },
  { token: "FLA", teams: ["Kent State Golden Flashes","Liberty Flames"] },
  { token: "GAM", teams: ["Jacksonville State Gamecocks","South Carolina Gamecocks"] },
  { token: "HUR", teams: ["Miami Hurricanes","Tulsa Golden Hurricane"] },
  { token: "HUS", teams: ["Northern Illinois Huskies","UConn Huskies"] },
  { token: "KNI", teams: ["Rutgers Scarlet Knights","UCF Knights"] },
  { token: "MIN", teams: ["Massachusetts Minutemen","UTEP Miners"] },
  { token: "OWL", teams: ["Florida Atlantic Owls","Kennesaw State Owls","Rice Owls","Temple Owls"] },
  { token: "PAN", teams: ["Florida International Panthers","Georgia State Panthers"] },
  { token: "RAI", teams: ["Middle Tennessee Blue Raiders","Texas Tech Red Raiders"] },
  { token: "WAR", teams: ["Hawai'i Rainbow Warriors","UL Monroe Warhawks"] },
  { token: "WIL", teams: ["Kentucky Wildcats","Northwestern Wildcats"] },
];

/** Lookup keys two schools both claimed, so neither got them. */
export const CFB_DROPPED_KEYS: ReadonlyArray<{
  readonly key: string;
  readonly tier: number;
  readonly teams: readonly string[];
}> = [
  { key: "aggies", tier: 1, teams: ["New Mexico State Aggies","Texas A&M Aggies","Utah State Aggies"] },
  { key: "BEA", tier: 2, teams: ["Cincinnati Bearcats","Missouri State Bears","Oregon State Beavers","Sam Houston Bearkats"] },
  { key: "bears", tier: 1, teams: ["Baylor Bears","Missouri State Bears"] },
  { key: "BOB", tier: 2, teams: ["Ohio Bobcats","Texas State Bobcats"] },
  { key: "bobcats", tier: 1, teams: ["Ohio Bobcats","Texas State Bobcats"] },
  { key: "broncos", tier: 1, teams: ["Boise State Broncos","Western Michigan Broncos"] },
  { key: "BUL", tier: 2, teams: ["Buffalo Bulls","Fresno State Bulldogs","Louisiana Tech Bulldogs","South Florida Bulls"] },
  { key: "bulldogs", tier: 1, teams: ["Fresno State Bulldogs","Georgia Bulldogs","Louisiana Tech Bulldogs","Mississippi State Bulldogs"] },
  { key: "bulls", tier: 1, teams: ["Buffalo Bulls","South Florida Bulls"] },
  { key: "cardinals", tier: 1, teams: ["Ball State Cardinals","Louisville Cardinals"] },
  { key: "COU", tier: 2, teams: ["BYU Cougars","Houston Cougars","Washington State Cougars"] },
  { key: "cougars", tier: 1, teams: ["BYU Cougars","Houston Cougars","Washington State Cougars"] },
  { key: "cowboys", tier: 1, teams: ["Oklahoma State Cowboys","Wyoming Cowboys"] },
  { key: "EAG", tier: 2, teams: ["Boston College Eagles","Eastern Michigan Eagles","Georgia Southern Eagles","Southern Miss Golden Eagles"] },
  { key: "eagles", tier: 1, teams: ["Boston College Eagles","Eastern Michigan Eagles","Georgia Southern Eagles"] },
  { key: "falcons", tier: 1, teams: ["Air Force Falcons","Bowling Green Falcons"] },
  { key: "GAM", tier: 2, teams: ["Jacksonville State Gamecocks","South Carolina Gamecocks"] },
  { key: "gamecocks", tier: 1, teams: ["Jacksonville State Gamecocks","South Carolina Gamecocks"] },
  { key: "HUR", tier: 2, teams: ["Miami Hurricanes","Tulsa Golden Hurricane"] },
  { key: "HUS", tier: 2, teams: ["Northern Illinois Huskies","UConn Huskies"] },
  { key: "huskies", tier: 1, teams: ["Northern Illinois Huskies","UConn Huskies","Washington Huskies"] },
  { key: "KNI", tier: 2, teams: ["Rutgers Scarlet Knights","UCF Knights"] },
  { key: "MIN", tier: 2, teams: ["Massachusetts Minutemen","UTEP Miners"] },
  { key: "mountaineers", tier: 1, teams: ["App State Mountaineers","West Virginia Mountaineers"] },
  { key: "OWL", tier: 2, teams: ["Florida Atlantic Owls","Kennesaw State Owls","Rice Owls","Temple Owls"] },
  { key: "owls", tier: 1, teams: ["Florida Atlantic Owls","Kennesaw State Owls","Rice Owls","Temple Owls"] },
  { key: "PAN", tier: 2, teams: ["Florida International Panthers","Georgia State Panthers"] },
  { key: "panthers", tier: 1, teams: ["Florida International Panthers","Georgia State Panthers","Pittsburgh Panthers"] },
  { key: "RAI", tier: 2, teams: ["Middle Tennessee Blue Raiders","Texas Tech Red Raiders"] },
  { key: "rebels", tier: 1, teams: ["Ole Miss Rebels","UNLV Rebels"] },
  { key: "spartans", tier: 1, teams: ["Michigan State Spartans","San José State Spartans"] },
  { key: "tigers", tier: 1, teams: ["Auburn Tigers","Clemson Tigers","LSU Tigers","Memphis Tigers","Missouri Tigers"] },
  { key: "trojans", tier: 1, teams: ["Troy Trojans","USC Trojans"] },
  { key: "WAR", tier: 2, teams: ["Hawai'i Rainbow Warriors","UL Monroe Warhawks"] },
  { key: "WIL", tier: 2, teams: ["Kentucky Wildcats","Northwestern Wildcats"] },
  { key: "wildcats", tier: 1, teams: ["Arizona Wildcats","Kansas State Wildcats","Kentucky Wildcats","Northwestern Wildcats"] },
  { key: "wolfpack", tier: 1, teams: ["NC State Wolfpack","Nevada Wolf Pack"] },
];
