/**
 * Seed draft-week signals for the 2026 NFL Draft (Apr 24–26).
 * Wipes old generic signals and seeds fresh, timely draft-week content.
 */
import { storage } from "./storage";

export async function seedSignals() {
  if (storage.signalExists()) return;

  const now = Date.now();
  const ago = (h: number) => new Date(now - h * 3600000).toISOString();

  const signals = [
    // ── PROSPECT RISERS ────────────────────────────────────────────
    {
      id: "sig-d01",
      title: "Fernando Mendoza medicals clear — Raiders locked at #1",
      slug: "mendoza-medicals-clear",
      player_name: "Fernando Mendoza",
      team: "Indiana / LV Raiders",
      topic: "draft_week",
      signal_type: "Medical clearance",
      status_tag: "verified" as const,
      confidence_score: 97,
      source_count: 14,
      verdict: "confirmed",
      summary: "All medical checks passed at the combine and Las Vegas Raiders private visit. No structural concerns. Multiple beat reporters confirm Raiders have informed Mendoza's agent he is the pick.",
      action_takeaway: "Lock Mendoza as #1 overall. Dynasty: max buy at current prices before the pick.",
      published_at: ago(1),
      is_featured: true,
      is_public: true,
    },
    {
      id: "sig-d02",
      title: "Jeremiyah Love stock surging — private visits with 3 top-5 teams",
      slug: "love-stock-surge",
      player_name: "Jeremiyah Love",
      team: "Notre Dame / TEN Titans",
      topic: "draft_week",
      signal_type: "Prospect riser",
      status_tag: "verified" as const,
      confidence_score: 91,
      source_count: 9,
      verdict: "likely",
      summary: "Love held private visits with Tennessee (#4), Cleveland (#7), and Pittsburgh (#9) in the 48h window. Titans offensive coordinator praised his pass-catching in pre-draft interviews. Historic pre-draft momentum for an RB.",
      action_takeaway: "Dynasty: aggressive buy. DFS Draft Day: tournament GPP value if he slides to 4–6 range.",
      published_at: ago(2),
      is_featured: false,
      is_public: true,
    },
    {
      id: "sig-d03",
      title: "Makai Lemon injury flag surfaced — teams requesting additional medicals",
      slug: "lemon-injury-flag",
      player_name: "Makai Lemon",
      team: "USC / KC Chiefs",
      topic: "draft_week",
      signal_type: "Medical concern",
      status_tag: "high-risk" as const,
      confidence_score: 84,
      source_count: 7,
      verdict: "rumor",
      summary: "Three teams in the 8–15 range have requested updated imaging on Lemon's 2025 shoulder. One AFC scout says 'there's real hesitation at the top of the second day.' Could slip from projected top-10 to 12–18 range.",
      action_takeaway: "Fade early in dynasty drafts until medicals resolve. Monitor closely night-of.",
      published_at: ago(3),
      is_featured: false,
      is_public: true,
    },
    // ── TEAM FIT / LANDING SPOT ────────────────────────────────────
    {
      id: "sig-d04",
      title: "Cardinals at #3 pivoting — Bain still favored but OT trade-up buzz real",
      slug: "cardinals-3-pivot",
      player_name: "Rueben Bain Jr.",
      team: "Miami / ARI Cardinals",
      topic: "draft_week",
      signal_type: "Team fit watch",
      status_tag: "verified" as const,
      confidence_score: 88,
      source_count: 8,
      verdict: "likely",
      summary: "Arizona has taken calls on trading down from #3, per two sources. If no trade materializes, Rueben Bain Jr. remains the favorite. Cowboys and Patriots both active as potential trade-up partners for a QB or OT.",
      action_takeaway: "Watch for a trade at #3 night-of. Bain's dynasty value unaffected; landing-spot matters less for elite EDGE.",
      published_at: ago(4),
      is_featured: false,
      is_public: true,
    },
    {
      id: "sig-d05",
      title: "Sonny Styles quietly emerging as Commanders' top LB target at #8",
      slug: "styles-commanders-fit",
      player_name: "Sonny Styles",
      team: "Ohio State / WAS Commanders",
      topic: "draft_week",
      signal_type: "Team fit confirmed",
      status_tag: "verified" as const,
      confidence_score: 87,
      source_count: 6,
      verdict: "likely",
      summary: "Washington DC Dan Quinn specifically requested Styles for a private visit and ran him through their linebacker-heavy scheme walk-through. Fit is described as 'perfect' by one Commanders source. No other team has shown equivalent interest.",
      action_takeaway: "Styles to Washington at #8 is the safest landing-spot bet on the board right now.",
      published_at: ago(5),
      is_featured: false,
      is_public: true,
    },
    // ── FREE AGENCY FALLOUT ────────────────────────────────────────
    {
      id: "sig-d06",
      title: "Kadyn Proctor Patriots fit amplified — OT market dried up in free agency",
      slug: "proctor-patriots-fa-fallout",
      player_name: "Kadyn Proctor",
      team: "Alabama / NE Patriots",
      topic: "draft_week",
      signal_type: "FA fallout signal",
      status_tag: "verified" as const,
      confidence_score: 89,
      source_count: 10,
      verdict: "confirmed",
      summary: "Patriots struck out on three offensive tackle targets in free agency this spring. Internal depth at LT is thin. Proctor is now universally considered the team's top priority at #6. New England has not taken calls to trade out.",
      action_takeaway: "Proctor to NE at #6 is a lock. Patriots urgency removes any slide risk.",
      published_at: ago(6),
      is_featured: false,
      is_public: true,
    },
    // ── DEPTH CHART / ROLE IMPLICATIONS ───────────────────────────
    {
      id: "sig-d07",
      title: "Caleb Downs to Giants — immediate FS1 role confirmed by coaching staff",
      slug: "downs-giants-fs1-role",
      player_name: "Caleb Downs",
      team: "Ohio State / NYG Giants",
      topic: "draft_week",
      signal_type: "Depth chart implication",
      status_tag: "verified" as const,
      confidence_score: 92,
      source_count: 11,
      verdict: "confirmed",
      summary: "Giants safety room is depleted after three veterans were cut or not re-signed this offseason. Coach Brian Daboll stated publicly they are drafting 'a starter, not a prospect.' Downs has been their guy since Senior Bowl.",
      action_takeaway: "Immediate starter in dynasty. Day-1 fantasy value in IDP formats. Highest-floor pick in top 10.",
      published_at: ago(7),
      is_featured: false,
      is_public: true,
    },
    {
      id: "sig-d08",
      title: "Spencer Fano medicals raised concerns — Browns doing due diligence at #7",
      slug: "fano-medicals-browns",
      player_name: "Spencer Fano",
      team: "Utah / CLE Browns",
      topic: "draft_week",
      signal_type: "Medical concern",
      status_tag: "speculative" as const,
      confidence_score: 79,
      source_count: 5,
      verdict: "rumor",
      summary: "Cleveland brought in two additional offensive line prospects for visits after Fano's combine measurements flagged a prior ankle procedure. Not enough to remove him from consideration but a second OT is on their radar at #7 as a contingency.",
      action_takeaway: "Slight slide risk for Fano. Monitor Browns pick-night. Spencer stays a first-round grade.",
      published_at: ago(9),
      is_featured: false,
      is_public: true,
    },
    // ── RUMOR / BUZZ ──────────────────────────────────────────────
    {
      id: "sig-d09",
      title: "Saints at #9 have active trade-up calls from QB-needy teams",
      slug: "saints-9-trade-buzz",
      player_name: "Mansoor Delane",
      team: "LSU / NO Saints",
      topic: "draft_week",
      signal_type: "Trade buzz",
      status_tag: "speculative" as const,
      confidence_score: 76,
      source_count: 4,
      verdict: "rumor",
      summary: "New Orleans has fielded multiple calls from teams wanting to jump into the top-10 for a QB or pass-rusher, per one league source. Saints are open to moving down if the return is right. Delane's board position unaffected — he goes in the 9–14 window regardless.",
      action_takeaway: "Don't anchor hard on Saints at #9 for Delane. Top-14 is safe. Beware of draft-night trade chaos.",
      published_at: ago(10),
      is_featured: false,
      is_public: true,
    },
    {
      id: "sig-d10",
      title: "Arvell Reese Jets visit — Reese reportedly 'loved the fit,' wants to stay local",
      slug: "reese-jets-fit",
      player_name: "Arvell Reese",
      team: "Ohio State / NYJ Jets",
      topic: "draft_week",
      signal_type: "Landing spot confirmed",
      status_tag: "verified" as const,
      confidence_score: 95,
      source_count: 12,
      verdict: "confirmed",
      summary: "Reese's private visit with the Jets was reported as exceptional by multiple insiders. The New York media market appeal is a genuine factor per his representation. Jets have not entertained trade-down offers at #2. Reese to Jets is now the most-confirmed landing spot outside of Mendoza.",
      action_takeaway: "Reese to Jets at #2 locked. Top dynasty EDGE target — immediate starter opposite Quinnen Williams.",
      published_at: ago(0.5),
      is_featured: false,
      is_public: true,
    },
    // ── PFF ANALYTICS ──────────────────────────────────────────────
    {
      id: "sig-d12",
      title: "PFF grades Mendoza as highest-rated QB prospect in 6 years of college grading",
      slug: "pff-mendoza-grade-2026",
      player_name: "Fernando Mendoza",
      team: "Indiana / LV Raiders",
      topic: "draft_week",
      signal_type: "PFF grade spike",
      status_tag: "verified" as const,
      confidence_score: 96,
      source_count: 1,
      verdict: "confirmed",
      summary: "Pro Football Focus released their final 2026 pre-draft grading. Mendoza earned a 96.2 overall passing grade — the highest PFF has recorded for a college QB in their six-year grading history. His pressure-to-clean pocket differential (the gap between how he grades under pressure vs. in a clean pocket) is the smallest PFF has ever measured, indicating elite pocket processing rather than system dependence.",
      action_takeaway: "Grade confirms the consensus: Mendoza is a generational prospect, not just a class leader. Max dynasty buy. DFS: locked as the first QB taken barring injury.",
      published_at: ago(4),
      is_featured: false,
      is_public: true,
    },
    {
      id: "sig-d13",
      title: "PFF pressure metrics back Rueben Bain Jr. as the top EDGE off the board",
      slug: "pff-bain-pressure-rate",
      player_name: "Rueben Bain Jr.",
      team: "Miami (FL) / ARI Cardinals",
      topic: "draft_week",
      signal_type: "PFF coverage / pressure metrics",
      status_tag: "verified" as const,
      confidence_score: 91,
      source_count: 1,
      verdict: "confirmed",
      summary: "PFF's 2026 edge rusher rankings put Bain at 94.7 pass-rush grade — the top mark in the class. His 26.1% pressure rate led all FBS edge defenders last season. In PFF's scheme-fit model, Bain's burst/bend profile grades highest in wide-9 alignments (Cards' base front), which is why Arizona has not fielded serious trade-down calls despite interest.",
      action_takeaway: "PFF data reinforces Bain staying at #3. Dynasty: buy the dip if ADP is inflated. DFS: Cardinals EDGE target for rookie showdowns.",
      published_at: ago(5),
      is_featured: false,
      is_public: true,
    },
    // ── SCOUTING / PERSONNEL — Chris Landry ──────────────────────
    {
      id: "sig-d14",
      title: "Landry Football scouting: Reese hand technique and scheme fit grade strongly for Jets",
      slug: "landry-reese-rush-plan",
      player_name: "Arvell Reese",
      team: "Ohio State / NYJ Jets",
      topic: "draft_week",
      signal_type: "Scouting evaluation",
      status_tag: "verified" as const,
      confidence_score: 90,
      source_count: 1,
      verdict: "confirmed",
      summary: "Chris Landry (former NFL coach/scout, Landry Football) evaluates Reese as a versatile pass rusher whose hand technique and burst profile translate well at the next level. Landry highlights Reese as a player who can win from multiple alignments. Jets wide-9 base is a favorable deployment for Reese's athleticism, and Landry grades the scheme fit as strong.",
      action_takeaway: "Scouting context supports the Jets fit. Reese's talent grade and scheme alignment are both in his favor at #2.",
      published_at: ago(3),
      is_featured: false,
      is_public: true,
    },
    {
      id: "sig-d15",
      title: "Landry Football scouting: Mendoza's film grades as NFL-ready across varied looks",
      slug: "landry-mendoza-processing",
      player_name: "Fernando Mendoza",
      team: "Indiana / LV Raiders",
      topic: "draft_week",
      signal_type: "Scouting evaluation",
      status_tag: "verified" as const,
      confidence_score: 94,
      source_count: 1,
      verdict: "confirmed",
      summary: "Chris Landry's film evaluation of Mendoza centers on pre-snap recognition and decision-making speed. Landry grades Mendoza's processing as NFL-ready, noting that his production held up consistently across varied defensive looks and game situations — not just in favorable scheme matchups. The evaluation supports a system-independent grade.",
      action_takeaway: "Scout film work backs the analytics consensus. Mendoza's decision-making grades well outside of scheme context.",
      published_at: ago(6),
      is_featured: false,
      is_public: true,
    },
    // ── COLLEGE ANALYSIS — Phil Steele ────────────────────────────
    {
      id: "sig-d16",
      title: "Phil Steele college preview: Love's production held up against ranked competition",
      slug: "steele-love-college-production",
      player_name: "Jeremiyah Love",
      team: "Notre Dame / TEN Titans",
      topic: "draft_week",
      signal_type: "College production context",
      status_tag: "verified" as const,
      confidence_score: 88,
      source_count: 1,
      verdict: "confirmed",
      summary: "Phil Steele's college statistical preview ranks Love among the top RBs in his 2025 class evaluations. Steele's research emphasizes Love's production against quality competition — his yards-per-carry in high-leverage games held up well against ranked opponents. Steele places weight on RBs whose numbers improve in big games rather than pad against weaker schedules. Love's profile fits that model.",
      action_takeaway: "College statistical context supports Love's grade. Production held up against quality competition, which is what Steele's model weights most.",
      published_at: ago(5),
      is_featured: false,
      is_public: true,
    },
    {
      id: "sig-d17",
      title: "Phil Steele college preview: Reese grades at the top of the EDGE class in Big Ten production",
      slug: "steele-reese-edge-ranking",
      player_name: "Arvell Reese",
      team: "Ohio State / NYJ Jets",
      topic: "draft_week",
      signal_type: "College ranking context",
      status_tag: "verified" as const,
      confidence_score: 89,
      source_count: 1,
      verdict: "confirmed",
      summary: "Phil Steele's college football statistical preview places Reese at the top of the EDGE class based on his Big Ten production. Steele's evaluations emphasize sack production and pressure rate against conference competition; Reese ranked among the FBS leaders in both. Steele's college rankings have historically tracked well against early NFL draft results at the EDGE position.",
      action_takeaway: "College statistical preview aligns with the NFL scouting grade. Reese is the top-ranked EDGE in both the analytics and college-preview views.",
      published_at: ago(8),
      is_featured: false,
      is_public: true,
    },
    // ── GENERAL INTEL ─────────────────────────────────────────────
    {
      id: "sig-d11",
      title: "Chiefs at #10 targeting WR — Lemon or Evan Stewart the live options",
      slug: "chiefs-wr-target",
      player_name: "Makai Lemon",
      team: "USC / KC Chiefs",
      topic: "draft_week",
      signal_type: "Team fit watch",
      status_tag: "verified" as const,
      confidence_score: 83,
      source_count: 7,
      verdict: "likely",
      summary: "Kansas City is exclusively targeting wide receiver at #10 after losing Rashee Rice to injury recurrence. Lemon is the top option if medicals clear; Evan Stewart is the safe floor. No interest in trading back.",
      action_takeaway: "Whoever Chiefs take at #10 has top WR1 upside in a Mahomes offense. Watch Lemon medical news.",
      published_at: ago(1.5),
      is_featured: false,
      is_public: true,
    },
  ];

  for (const s of signals) {
    try {
      storage.createSignal(s);
    } catch (e) {
      // already exists
    }
  }

  // Source notes for the featured signal
  const notes = [
    {
      signal_id: "sig-d01",
      source_name: "Adam Schefter",
      source_type: "reporter",
      trust_score: 96,
      note: "Full medical clearance confirmed. No structural issues found. Raiders have informed Mendoza's camp.",
    },
    {
      signal_id: "sig-d01",
      source_name: "Ian Rapoport",
      source_type: "reporter",
      trust_score: 94,
      note: "Private visit described as a 'formality.' Pick is locked barring an unprecedented last-minute trade.",
    },
    {
      signal_id: "sig-d01",
      source_name: "NFL Network",
      source_type: "official",
      trust_score: 91,
      note: "Draft analysts unanimous: Mendoza #1 overall, Raiders on the clock Thursday night.",
    },
    {
      signal_id: "sig-d12",
      source_name: "Pro Football Focus",
      source_type: "analytics",
      trust_score: 91,
      note: "PFF 2026 pre-draft grades: Mendoza 96.2 overall — highest college QB grade in PFF history.",
    },
    {
      signal_id: "sig-d13",
      source_name: "Pro Football Focus",
      source_type: "analytics",
      trust_score: 91,
      note: "PFF pass-rush grade 94.7, pressure rate 26.1% — best in FBS 2025. Scheme fit: wide-9 optimal.",
    },
    {
      signal_id: "sig-d14",
      source_name: "Landry Football",
      source_type: "scouting",
      trust_score: 88,
      note: "Chris Landry (former NFL coach/scout): Reese hand technique and burst profile grade well. Wide-9 scheme deployment rated as a strong fit for his athleticism.",
    },
    {
      signal_id: "sig-d15",
      source_name: "Landry Football",
      source_type: "scouting",
      trust_score: 88,
      note: "Chris Landry film evaluation: Mendoza's processing and decision-making grade as NFL-ready. Production held up across varied defensive looks, supporting a system-independent grade.",
    },
    {
      signal_id: "sig-d16",
      source_name: "Phil Steele",
      source_type: "college_analyst",
      trust_score: 85,
      note: "Phil Steele college rankings: Love grades among top RBs in the class. YPC held up well against ranked opponents, which Steele's model weights heavily.",
    },
    {
      signal_id: "sig-d17",
      source_name: "Phil Steele",
      source_type: "college_analyst",
      trust_score: 85,
      note: "Phil Steele college preview: Reese top-ranked EDGE in the class per Big Ten production metrics. Ranked among FBS leaders in sacks and pressure rate against conference competition.",
    },
  ];

  for (const n of notes) {
    try {
      storage.createSourceNote({ ...n, id: `note-${n.signal_id}-${n.source_name.replace(/\s/g, "")}` });
    } catch (e) {}
  }

  console.log("[seed] 17 draft-week signals seeded (incl. 2 PFF analytics, 2 Landry scouting, 2 Phil Steele college signals)");
}
